# -*- coding: utf-8 -*-
"""yoloobjdetc2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U4BCVHIDs2u_DcQ9io7dFSne9uwxUN2D

# Mounting google drive first for a storage and GPU
"""

from google.colab import drive
drive.mount('/content/gdrive')

"""# Checking the GPU compatibility"""

!nvidia-smi

"""# Cloning the Darknet GitHub repository"""

import os
os.environ['PATH'] += ':/usr/local/cuda/bin'
!rm -fr darknet
!git clone https://github.com/AlexeyAB/darknet/

"""# Installing gcc and g++ for execution of the Darknet repo"""

!apt install gcc-5 g++-5 -y
!ln -s /usr/bin/gcc-5 /usr/local/cuda/bin/gcc 
!ln -s /usr/bin/g++-5 /usr/local/cuda/bin/g++

"""# Entering darknet folder, enabling GPU and compile the entire thing."""

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet
!sed -i 's/GPU=0/GPU=1/g' Makefile
!sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
!make

"""# Get the YOLO Weights file"""

!wget https://pjreddie.com/media/files/yolov3.weights
!chmod a+x ./darknet

"""# Checking the working Directory"""

!pwd

"""# Mounting Google Drive to Darknet folder"""

from google.colab import drive
drive.mount('/content/drive')

"""Optional command to update the contents if asked to"""

!apt-get update

"""# Support Libraries like OpenCV-Dev, Numpy, LibJpeg and more."""

!apt install ffmpeg libopencv-dev libgtk-3-dev python-numpy python3-numpy libdc1394-22 libdc1394-22-dev libjpeg-dev libtiff5-dev libavcodec-dev libavformat-dev libswscale-dev libxine2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libv4l-dev libtbb-dev qtbase5-dev libfaac-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev x264 v4l-utils unzip

"""# Uploading .mp4 file to Darknet folder"""

from google.colab import files

uploaded = files.upload()

"""# Training the dataset"""

!./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -dont_show test.mp4 -i 0 -out_filename output1.avi -thresh 0.7

"""# Downloading the converted .avi file"""

from google.colab import files
files.download('output1.avi')